version: "3.8"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  celery_worker:
    build: .
    command: celery -A celery_config worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - app-network

  celery_beat:
    build: .
    command: celery -A celery_config beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - app-network

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge
